ARG TOR_VERSION="0.4.7.13"
ARG TOR_IMAGE="quay.io/bugfest/tor"

FROM quay.io/bugfest/tor-daemon-manager:latest as builder

FROM ${TOR_IMAGE}:${TOR_VERSION} as tor

COPY --from=builder /root/tor-local-manager .

ENTRYPOINT ["./tor-local-manager"]
